// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: province.sql

package db

import (
	"context"
)

const getProvince = `-- name: GetProvince :one
SELECT id, name FROM provinces
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProvince(ctx context.Context, name string) (Province, error) {
	row := q.db.QueryRowContext(ctx, getProvince, name)
	var i Province
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
